# Form implementation generated from reading ui file 'mau.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(900, 600)
        home.setStyleSheet("background-image: url(backgroundbh.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=home)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(130, 480, 640, 41))
        font = QtGui.QFont()
        font.setFamily("arcade_classic_2")
        font.setPointSize(10)
        font.setBold(True)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    margin-left: 50px;\n"
"    margin-right: 50px;\n"
"    \n"
"    \n"
"    background-color: rgb(176, 205, 211);\n"
"    border: 5px solid #0e5d88;\n"
"    color: rgb(14, 102, 153);\n"
"    border-color: ;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    font-family: \'arcade_classic_2\';\n"
"    text-color: #03045e;\n"
"    \n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    \n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0.272727 rgba(240, 128, 14, 255), stop:1 rgba(255, 221, 0, 255));\n"
"}    ")
        self.progressBar.setProperty("value", 42)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.label.setStyleSheet("border-image: url(:/newPrefix/backgroundbh new.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 530, 321, 16))
        font = QtGui.QFont()
        font.setFamily("arcade_classic_2")
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"     text-align: center;\n"
"    font-family: \'arcade_classic_2\';\n"
"    text-color: #fed501;\n"
"    color: rgb(254, 213, 1);\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.progressBar.raise_()
        self.label_2.raise_()
        home.setCentralWidget(self.centralwidget)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "MainWindow"))
        self.label_2.setText(_translate("home", "Loading..."))
